name: Conditions
on: push
jobs:
  skip-on-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
        if: ${{ contains(github.run_id, '8')}} # Change Status 1
      - run: echo "${{github.run_id}}"