name: GITHUB_OUTPUT
on: push
jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - id: source
        run: echo "result=HELLO" >> "${GITHUB_OUTPUT}"
      - env:
          RESLUT: ${{ steps.source.outputs.result}}
        run: echo "${RESLUT}"